include::vars.adoc[]

The `pod` corresponding to each instance of your application is ephemeral. If it dies it is not resurrected. The `replicaset` ensures that a `pod` that has died is replaced with a new instance, as well as ensuring the correct number of `pods` exist when scaling the number of replicas up or down. When a new `pod` is created, it will always have a new name.

Each `pod`, as well as having a unique name, is also assigned it's own IP address. You can see the IP addresses assigned to each `pod` by running:

[.console-input]
[source,execute]
----
kubectl get pods -o wide
----

[.console-output]
[source]
----
NAME                        READY   STATUS    RESTARTS   AGE    IP             NODE                            NOMINATED NODE   READINESS GATES
parksmap-86f598b786-dvr4m   1/1     Running   0          122m   10.132.0.197   control-plane-cluster-dvtv2-1   <none>           <none>
----

See what happens when you delete your pod. Use the pod name from the previous output and delete it with `kubectl delete pod`.

[.console-output]
[source]
----
kubectl delete pod/parksmap-86f598b786-dvr4m
pod "parksmap-86f598b786-dvr4m" deleted
----

Now check for running pods again and you should see a new pod has started in its place. It also has a different IP address!

[.console-output]
[source]
----
kubectl get pods -o wide
NAME                        READY   STATUS    RESTARTS   AGE   IP            NODE                            NOMINATED NODE   READINESS GATES
parksmap-86f598b786-tl25c   1/1     Running   0          5s    10.132.1.27   control-plane-cluster-dvtv2-1   <none>           <none>
----

These IP addresses are only accessible within the Kubernetes cluster. Depending on the Kubernetes networking configuration, they may only be accessible from applications running in the same namespace.

Like with the names of `pods`, the IP addresses in use for an application will not stay the same over time. When a `pod` dies and is replaced, it can receive a completely different IP address. IP addresses cannot be relied upon for communicating between components in an application.

To add a stable IP address and hostname for an application, a `service` resource needs to be created. The IP address of a `service` will map to the set of `pods` which make up your application, with traffic to the IP address of the service being load balanced across the `pods`.

As with creating a `deployment`, the `kubectl` program provides convenience methods for creating a `service`. These are `kubectl expose` and `kubectl create service`. 

When used to create the resource object, this will result in a `service` named `parksmap` being created that will expose port 8080 on the `pods`.

[.console-input]
[source,execute]
----
kubectl expose deployment/parksmap --port 8080
----

When used to create the resource object, this will result in a `service` named `parksmap` being created. The `ports` definition says that port 8080 will be exposed, with it mapping to port 8080 on the `pods`.

We can view the newly created service:


[.console-input]
[source,execute]
----
kubectl get service -o wide
----

This will display output similar to:

[.console-output]
[source]
----
NAME       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE     SELECTOR
parksmap   ClusterIP   172.31.53.168   <none>        8080/TCP   3m18s   app=parksmap
----

You can see that the service has it's own IP address.

Another application running in the same namespace can connect on this IP address and port 8080 to talk to the front end web application.

The `service` will know what the corresponding `pods` are that traffic should be load balanced across by virtue of the label selector defined in the `service`. Another useful use case of labelling in kubernetes. This is the `spec.selector` value:

[.console-output]
[source]
----
  selector:
    app: parksmap
----

This means that the IP addresses for the `pods` resulting from a query of:

[.console-input]
[source,execute]
----
kubectl get pods -l app=parksmap -o name
----

will be registered as endpoints against the `service`.

You can see the IP addresses of the `pods` registered against the `service` by running:

[.console-input]
[source,execute]
----
kubectl get endpoints parksmap
----

This will display output similar to:

[.console-output]
[source]
----
NAME       ENDPOINTS                           AGE
parksmap   10.132.2.54:8080   10m
----

You see the IP address of the pods along with the service port defined.

Although the IP address will not change for the life of the `service` object, the IP should still not be used. Imagine the problems it would cause when moving applications through environments. Instead, a hostname corresponding to the `service` should be used. The hostname is the name of the `service`, is registered within an internal DNS in the Kubernetes cluster, and can be used by any application within the cluster.

For an application running in the same namespace, an un-qualifed hostname can be used. In this case `parksmap` would be the hostname. If networking in the cluster is configured to allow access across namespaces, an application in a different namespace can use the name with subdomain matching the name of the namespace, and the further domain of `.svc`.

For the front end web application you have deployed, the URL for accessing it would be:

`http://parksmap.wksp-{user}.svc:8080`


You can test it works by running:

`curl http://parksmap.wksp-{user}.svc:8080`

The response you see is a ton of html and javascript code. That's fine, it's for the browser and shows that it's working.

Note that this still isn't accessible outside of the Kubernetes cluster, extra steps are required to expose a `service` outside of the cluster. The `curl` command only works because the terminal you are using is running as a `pod` in the same Kubernetes cluster.
