The Parksmap application uses a MongoDB database to store details for national parks. Currently, the databases data is stored inside the running container, this means the storage in the container is ephemeral, when a  database `pod` is killed, the data is lost. Not really the desired outcome of a database.

Lets test this out.

In your terminal window, type:

[.console-input]
[source,execute]
----
kubectl delete pod --force -l role=database
----

The MongoDB pod has been replaced and we have lost the ephemeral database - Refresh the Parksmap application in your browser. You should see that all the National Parks are gone!

A resource that can be associated with any 'pod' is a persistent volume. The data stored in the persistent volume will survive when the pod is killed and restarted. `Persistent volumes` are typically stored in some form of shared storage and is configured by the kubernetes platform owner. You define the configuration in the template section of the deployment yaml file. It will then roll the configuration out to the resulting `pods`

To add persistent storage to an application, the first step is that you need to create a `persistent volume claim`. This tells Kubernetes that you need storage, how big the volume needs to be and what type of storage is required.

The resource definition for the persistent volume claim we need to use can be seen by running:

[.console-input]
[source,execute]
----
cat database/persistentvolumeclaim.yaml
----

You should see that it contains:

[.console-output]
[source]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: national-parks-database
  labels:
    app: national-parks-database
    role: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
----

This says that the storage should be at least of size 1Gi and that the access mode should be `ReadWriteOnce`.

Kubernetes supports three different access modes for storage.

* `ReadWriteOnce` (RWO) - The volume can be mounted as read/write by a single node.
* `ReadOnlyMany` (ROX) - The volume can be mounted as read-only by many nodes.
* `ReadWriteMany` (RWX) - The volume can be mounted as read/write by many nodes.

What access modes for storage are available will depend on the Kubernetes cluster.

For the database we are using, because we want to be able to run a single instance, we need storage with access mode `ReadWriteOnce`. 

Create the persistent volume claim by running the following command:

[.console-input]
[source,execute]
----
kubectl apply -f database/persistentvolumeclaim.yaml
----

You should get confirmation telling you that the persistent volume claim has been created.

If you want to use some of the commands you've learned to confirm the creation then please feel free to.

In addition to creating the persistent volume claim, the `deployment` needs to be updated.

At `spec.template.spec.volumes` in the `deployment` we need to add:

[.console-output]
[source]
----
      volumes:
      ....
        - name: national-parks-database
          persistentVolumeClaim:
            claimName: national-parks-database
      ....
----

This indicates the persistent volume claim is to be used.

At `spec.template.spec.containers.volumeMounts`, we need to add:

[.console-output]
[source]
----
        volumeMounts:
        ....
          volumeMounts:
            - name: national-parks-database
              mountPath: /data/configdb
            - name: national-parks-database
              mountPath: /data/db
        ....
----

This indicates that the persistent volume should be mounted at the path `/data` in the container.

To see the updated `deployment` configuration run:

[.console-input]
[source,execute]
----
cat database-v1/deployment.yaml
----

To apply the configuration changes run:

[.console-input]
[source,execute]
----
kubectl apply -f database-v1/deployment.yaml
----

You should see confirmation that the deployment was configured. The changes to the deployment have triggered the MongoDB pod to be re-created with the new configuration. Wait for the new pod to start:

[.console-input]
[source,execute]
----
watch kubectl get po -l role=database
----

When the pod reaches a *running* state, the database should now be able to recover from failures, restarts and so on.

Test it out.

Firstly, lets load the data back info the database. In the terminal window, run 

[.console-input]
[source, execute, subs="attributes"]
----
curl http://nationalparks-py.wksp-{user}.svc.cluster.local:8080/ws/data/load
----

Refresh the parksmap page in the `browser`. You should see national parks appearing on the map.

Now, kill the database pod again by running

[.console-input]
[source,execute]
----
kubectl delete pod --force -l role=database
----

NOTE: you are using the --force flag to terminate the pod quickly. Delete pod is a controlled shutdown which in our case means the terminating pod holds on to a mongodb lock file in the persistent volume. Without force, it will cause the new starting pod to fail as it cannot get a hold of the lock file.

NOTE: For the keen eyed, you might also spot that the deployment strategy has changed to recreate. Rolling updates were briefly mention earlier. Recreate means that any deployment changes result in a complete shutdown of the database (in this case). This, again, is to ensure that any old deployment doesn't hold on to the persistent volume lock file. 

Check the status of the pod to make sure it is running by typing the following into the terminal window:

[.console-input]
[source,execute]
----
kubectl get pods -l role=database
----

Finally, refresh the parksmap page in the browser again. The parks data should now be persistent and still visible!