Each instance of an application runs in it's own `pod`.

As you have already seen, you can list the `pods` for the front end web application using:

[.console-input]
[source,execute]
----
kubectl get pods -l app=parksmap -o name
----

To access the log output for an application, you can use the name of the deployment with the `kubectl logs` command.

[.console-input]
[source,execute]
----
kubectl logs deployment/parksmap
----

We can also look at an individual pod. As we have multiple pods, we need to grab just one of the names.

[.console-input]
[source,execute]
----
POD=`kubectl get pod -l app=parksmap -o name | head -1`
----

The command above just gets the name of the first pod from the output and stores it in an environemnt variable. if you don't want to be flash then you can just copy and paste the pod name directly into the `kubectl logs` command.

run `kubectl logs`:

[.console-input]
[source,execute]
----
kubectl logs $POD
----

Were there multiple containers in the `pod`, you would need to name the container using the `-c` or `--container` option. Alternatively, you could use the `--all-containers` option to fetch logs from application process running in any of the containers.

If you wanted to follow the output of the running application, you can use the `-f` or `--follow` option.

When you have multiple replicas of your application, you would need to fetch the application logs from each `pod`. A Kubernetes cluster may optionally have a service deployed for aggregated logging, in which case you could access that service to view logs for all instances of the application at the same time.